const fs = require('fs')
var input = fs.readFileSync('inpt.md', 'utf8').split()
let x = parseFloat(input[0])
let y = parseFloat(input[1])
if (x > 0 && y > 0)
    console.log("Q1")
else if (x < 0 && y < 0)
    console.log("Q3")
else if (x > 0 && y < 0)
    console.log("Q4")
else if (x < 0 && y > 0)
    console.log("Q2")
else if (x === 0 && y > 0|| x===0 && y < 0)
    console.log("Eixo Y")
else if (y === 0 && x > 0 ||  y===0 && x < 0)
    console.log("Eixo X")
else
    console.log("Origem")